[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    info
    Parsers_File /fluent-bit/etc/parsers.conf

[INPUT]
    Name              tail
    Path              /var/log/containers/*api-gateway*.log
    Tag               api-gateway
    Parser            docker
    Refresh_Interval  2
    Mem_Buf_Limit     50MB

[INPUT]
    Name              tail
    Path              /var/log/containers/*product-service*.log
    Tag               product-service
    Parser            docker
    Refresh_Interval  2
    Mem_Buf_Limit     50MB

[INPUT]
    Name              tail
    Path              /var/log/containers/*order-service*.log
    Tag               order-service
    Parser            docker
    Refresh_Interval  2
    Mem_Buf_Limit     50MB

[INPUT]
    Name              tail
    Path              /var/log/containers/*user-service*.log
    Tag               user-service
    Parser            docker
    Refresh_Interval  2
    Mem_Buf_Limit     50MB

[INPUT]
    Name              tail
    Path              /var/log/containers/*cart-service*.log
    Tag               cart-service
    Parser            docker
    Refresh_Interval  2
    Mem_Buf_Limit     50MB

[FILTER]
    Name       parser
    Match      *
    Key_Name   log
    Parser     json
    Reserve_Data True

[FILTER]
    Name       modify
    Match      *
    Add        tag $TAG

[OUTPUT]
    Name              kafka
    Match             *
    Brokers           host.docker.internal:9092,cognitive-redpanda:29092
    Topics            raw.logs
    Timestamp_Key     timestamp
    Retry_Limit       3
    Format            json
